-- gerado por seed_kpi_config.py — não editar à mão
BEGIN;
INSERT INTO kpi_configurations ("UnitId","ClinicId","KpiKey","SourceType","ConfigJson","IsCustom","DisplayType","SortOrder","CreatedAt","UpdatedAt") VALUES (16,8025,'total_leads','created','{}',false,'number',0,now(),now()) ON CONFLICT ("UnitId","KpiKey") DO UPDATE SET "SourceType"=EXCLUDED."SourceType", "ConfigJson"=EXCLUDED."ConfigJson", "UpdatedAt"=now();
INSERT INTO kpi_configurations ("UnitId","ClinicId","KpiKey","SourceType","ConfigJson","IsCustom","DisplayType","SortOrder","CreatedAt","UpdatedAt") VALUES (16,8025,'cadastro','custom_field_count','{"fieldId": 2450194, "matchValues": ["Cadastro"]}',false,'number',0,now(),now()) ON CONFLICT ("UnitId","KpiKey") DO UPDATE SET "SourceType"=EXCLUDED."SourceType", "ConfigJson"=EXCLUDED."ConfigJson", "UpdatedAt"=now();
INSERT INTO kpi_configurations ("UnitId","ClinicId","KpiKey","SourceType","ConfigJson","IsCustom","DisplayType","SortOrder","CreatedAt","UpdatedAt") VALUES (16,8025,'resgate','custom_field_count','{"fieldId": 2450194, "matchValues": ["Resgate"]}',false,'number',0,now(),now()) ON CONFLICT ("UnitId","KpiKey") DO UPDATE SET "SourceType"=EXCLUDED."SourceType", "ConfigJson"=EXCLUDED."ConfigJson", "UpdatedAt"=now();
INSERT INTO kpi_configurations ("UnitId","ClinicId","KpiKey","SourceType","ConfigJson","IsCustom","DisplayType","SortOrder","CreatedAt","UpdatedAt") VALUES (16,8025,'agendados','custom_field_count','{"fieldId": 2450220, "matchValues": ["Sim"]}',false,'number',0,now(),now()) ON CONFLICT ("UnitId","KpiKey") DO UPDATE SET "SourceType"=EXCLUDED."SourceType", "ConfigJson"=EXCLUDED."ConfigJson", "UpdatedAt"=now();
INSERT INTO kpi_configurations ("UnitId","ClinicId","KpiKey","SourceType","ConfigJson","IsCustom","DisplayType","SortOrder","CreatedAt","UpdatedAt") VALUES (16,8025,'interacoes','custom_field_count','{"fieldId": 2450182, "matchValues": ["Sim"]}',false,'number',0,now(),now()) ON CONFLICT ("UnitId","KpiKey") DO UPDATE SET "SourceType"=EXCLUDED."SourceType", "ConfigJson"=EXCLUDED."ConfigJson", "UpdatedAt"=now();
INSERT INTO kpi_configurations ("UnitId","ClinicId","KpiKey","SourceType","ConfigJson","IsCustom","DisplayType","SortOrder","CreatedAt","UpdatedAt") VALUES (16,8025,'no_show','franquia','{"metric": "no_show"}',false,'number',0,now(),now()) ON CONFLICT ("UnitId","KpiKey") DO UPDATE SET "SourceType"=EXCLUDED."SourceType", "ConfigJson"=EXCLUDED."ConfigJson", "UpdatedAt"=now();
INSERT INTO kpi_configurations ("UnitId","ClinicId","KpiKey","SourceType","ConfigJson","IsCustom","DisplayType","SortOrder","CreatedAt","UpdatedAt") VALUES (16,8025,'consultas','franquia','{"metric": "consultas"}',false,'number',0,now(),now()) ON CONFLICT ("UnitId","KpiKey") DO UPDATE SET "SourceType"=EXCLUDED."SourceType", "ConfigJson"=EXCLUDED."ConfigJson", "UpdatedAt"=now();
INSERT INTO kpi_configurations ("UnitId","ClinicId","KpiKey","SourceType","ConfigJson","IsCustom","DisplayType","SortOrder","CreatedAt","UpdatedAt") VALUES (16,8025,'tratamentos','franquia','{"metric": "tratamentos"}',false,'number',0,now(),now()) ON CONFLICT ("UnitId","KpiKey") DO UPDATE SET "SourceType"=EXCLUDED."SourceType", "ConfigJson"=EXCLUDED."ConfigJson", "UpdatedAt"=now();
COMMIT;
