// <auto-generated />
using System;
using LeadAnalytics.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LeadAnalytics.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260509044855_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LeadAnalytics.Api.Models.AppConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AppConfigurations");
                });

            modelBuilder.Entity("LeadAnalytics.Api.Models.Attendant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<int>("ExternalId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<int>("UnitId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("UnitId");

                    b.ToTable("attendants", (string)null);
                });

            modelBuilder.Entity("LeadAnalytics.Api.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AttendanceStatus")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("AttendanceStatusAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Blocked")
                        .HasColumnType("boolean");

                    b.Property<string>("Conexao")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ConsultationAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ConsultationRegisteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Etapa")
                        .HasColumnType("text");

                    b.Property<int?>("ImportBatchId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ImportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastMessageAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MetaAdsIdsJson")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("PhoneNormalized")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneRaw")
                        .HasColumnType("text");

                    b.Property<string>("TagsJson")
                        .HasColumnType("text");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ImportBatchId");

                    b.HasIndex("TenantId", "AttendanceStatus");

                    b.HasIndex("TenantId", "LastMessageAt");

                    b.HasIndex("TenantId", "Origem");

                    b.HasIndex("TenantId", "PhoneNormalized")
                        .IsUnique();

                    b.HasIndex("PhoneNormalized", "CreatedAt", "Id");

                    b.ToTable("contacts", (string)null);
                });

            modelBuilder.Entity("LeadAnalytics.Api.Models.ImportBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedCount")
                        .HasColumnType("integer");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("integer");

                    b.Property<string>("ErrorsJson")
                        .HasColumnType("text");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SkippedCount")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<int>("TotalRows")
                        .HasColumnType("integer");

                    b.Property<int>("UpdatedCount")
                        .HasColumnType("integer");

                    b.Property<int?>("UploadedByUserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CreatedAt");

                    b.ToTable("import_batches", (string)null);
                });

            modelBuilder.Entity("LeadAnalytics.Api.Models.Lead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .HasColumnType("text");

                    b.Property<string>("AttendanceStatus")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("AttendanceStatusAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("AttendantId")
                        .HasColumnType("integer");

                    b.Property<string>("Campaign")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConversationState")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ConvertedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Cpf")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentStage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("CurrentStageId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<int>("ExternalId")
                        .HasColumnType("integer");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<bool>("HasAppointment")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasHealthInsurancePlan")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasPayment")
                        .HasColumnType("boolean");

                    b.Property<int?>("IdChannelIntegration")
                        .HasColumnType("integer");

                    b.Property<string>("IdFacebookApp")
                        .HasColumnType("text");

                    b.Property<string>("LastAdId")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observations")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tags")
                        .HasColumnType("text");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<string>("TrackingConfidence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UnitId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AttendantId");

                    b.HasIndex("UnitId");

                    b.HasIndex("ExternalId", "TenantId")
                        .IsUnique();

                    b.HasIndex("TenantId", "AttendanceStatus");

                    b.HasIndex("TenantId", "CreatedAt");

                    b.ToTable("leads", (string)null);
                });

            modelBuilder.Entity("LeadAnalytics.Api.Models.LeadAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("AttendantId")
                        .HasColumnType("integer");

                    b.Property<int>("LeadId")
                        .HasColumnType("integer");

                    b.Property<string>("Stage")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AttendantId");

                    b.HasIndex("LeadId");

                    b.ToTable("lead_assignments", (string)null);
                });

            modelBuilder.Entity("LeadAnalytics.Api.Models.LeadAttribution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Confidence")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CtwaClid")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("LeadId")
                        .HasColumnType("integer");

                    b.Property<string>("MatchType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("MatchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OriginEventId")
                        .HasColumnType("integer");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SourceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SourceType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OriginEventId");

                    b.ToTable("LeadAttributions");
                });

            modelBuilder.Entity("LeadAnalytics.Api.Models.LeadConversation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AttendantId")
                        .HasColumnType("integer");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConversationState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LeadId")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AttendantId");

                    b.HasIndex("LeadId");

                    b.ToTable("lead_conversations", (string)null);
                });

            modelBuilder.Entity("LeadAnalytics.Api.Models.LeadInteraction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LeadConversationId")
                        .HasColumnType("integer");

                    b.Property<string>("Metadata")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LeadConversationId");

                    b.ToTable("lead_interactions", (string)null);
                });

            modelBuilder.Entity("LeadAnalytics.Api.Models.LeadStageHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LeadId")
                        .HasColumnType("integer");

                    b.Property<int>("StageId")
                        .HasColumnType("integer");

                    b.Property<string>("StageLabel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LeadId");

                    b.ToTable("lead_stage_histories", (string)null);
                });

            modelBuilder.Entity("LeadAnalytics.Api.Models.OriginEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Confidence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("CtwaClid")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Headline")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MessageId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("MessageTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("Processed")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SourceType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("TenantId")
                        .HasColumnType("integer");

                    b.Property<int?>("WebhookEventId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WebhookEventId");

                    b.ToTable("OriginEvents");
                });

            modelBuilder.Entity("LeadAnalytics.Api.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(12,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DownPayment")
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal>("InstallmentValue")
                        .HasColumnType("numeric(12,2)");

                    b.Property<int>("Installments")
                        .HasColumnType("integer");

                    b.Property<int>("LeadId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<string>("Treatment")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("TreatmentDurationMonths")
                        .HasColumnType("integer");

                    b.Property<decimal>("TreatmentValue")
                        .HasColumnType("numeric(12,2)");

                    b.Property<int?>("UnitId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LeadId");

                    b.HasIndex("UnitId");

                    b.HasIndex("TenantId", "PaidAt");

                    b.HasIndex("TenantId", "UnitId");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("LeadAnalytics.Api.Models.PaymentSplit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(12,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("InstallmentValue")
                        .HasColumnType("numeric(12,2)");

                    b.Property<int>("Installments")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("PaymentId")
                        .HasColumnType("integer");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("PaymentId");

                    b.HasIndex("PaymentId", "PaymentMethod");

                    b.ToTable("payment_splits", (string)null);
                });

            modelBuilder.Entity("LeadAnalytics.Api.Models.SdrAgendaEvento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("HoraFim")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("HoraInicio")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ResponsavelLogin")
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<int?>("SdrLeadId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("agendado");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SdrLeadId");

                    b.HasIndex("TenantId", "Data");

                    b.HasIndex("TenantId", "Status");

                    b.ToTable("sdr_agenda_eventos", (string)null);
                });

            modelBuilder.Entity("LeadAnalytics.Api.Models.SdrAuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("AfterJson")
                        .HasColumnType("text");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("UserEmail")
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("TenantId", "Action");

                    b.HasIndex("TenantId", "CreatedAt");

                    b.HasIndex("TenantId", "EntityType", "EntityId");

                    b.ToTable("sdr_audit_logs", (string)null);
                });

            modelBuilder.Entity("LeadAnalytics.Api.Models.SdrConsulta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataConsulta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("FechouTratamento")
                        .HasColumnType("boolean");

                    b.Property<string>("MotivoNaoFechamento")
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("Pago")
                        .HasColumnType("boolean");

                    b.Property<int>("SdrLeadId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<string>("TipoTratamentoIndicado")
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ValorConsulta")
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal?>("ValorTratamento")
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("SdrLeadId");

                    b.HasIndex("TenantId", "DataConsulta");

                    b.ToTable("sdr_consultas", (string)null);
                });

            modelBuilder.Entity("LeadAnalytics.Api.Models.SdrLead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AgendouConsulta")
                        .HasColumnType("boolean");

                    b.Property<int?>("AttendantId")
                        .HasColumnType("integer");

                    b.Property<string>("Clinica")
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<string>("CloudiaFields")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CloudiaReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CloudiaWebhookEvent")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataAgendamento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataModificacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataOrigem")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ExternalId")
                        .HasColumnType("integer");

                    b.Property<int?>("ImportBatchId")
                        .HasColumnType("integer");

                    b.Property<bool>("Interacao")
                        .HasColumnType("boolean");

                    b.Property<string>("Login")
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<string>("MotivoNaoAgendamento")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<string>("NomeResponsavel")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ReviewedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Situacao")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("cloudia");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("pendente_revisao");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TipoResgate")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int?>("UnitId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ImportBatchId");

                    b.HasIndex("ReviewedByUserId");

                    b.HasIndex("UnitId");

                    b.HasIndex("TenantId", "CreatedAt");

                    b.HasIndex("TenantId", "ExternalId")
                        .IsUnique()
                        .HasFilter("\"ExternalId\" IS NOT NULL");

                    b.HasIndex("TenantId", "Source");

                    b.HasIndex("TenantId", "Status");

                    b.ToTable("sdr_leads", (string)null);
                });

            modelBuilder.Entity("LeadAnalytics.Api.Models.SdrMeta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<string>("Mes")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<decimal>("MetaValor")
                        .HasColumnType("numeric(12,2)");

                    b.Property<int>("QtdTotal")
                        .HasColumnType("integer");

                    b.Property<int>("RealCadastro")
                        .HasColumnType("integer");

                    b.Property<int>("RealResgate")
                        .HasColumnType("integer");

                    b.Property<string>("Secretaria")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<string>("Unidade")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Mes");

                    b.HasIndex("TenantId", "Mes", "Login")
                        .IsUnique();

                    b.ToTable("sdr_metas", (string)null);
                });

            modelBuilder.Entity("LeadAnalytics.Api.Models.SdrRecebimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataRecebimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FormaPagamento")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.Property<int?>("SdrConsultaId")
                        .HasColumnType("integer");

                    b.Property<int?>("SdrTratamentoId")
                        .HasColumnType("integer");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("SdrConsultaId");

                    b.HasIndex("SdrTratamentoId");

                    b.HasIndex("TenantId", "DataRecebimento");

                    b.ToTable("sdr_recebimentos", (string)null);
                });

            modelBuilder.Entity("LeadAnalytics.Api.Models.SdrTarefa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ConcludedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Prioridade")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("media");

                    b.Property<string>("ResponsavelLogin")
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<int?>("SdrLeadId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("pendente");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SdrLeadId");

                    b.HasIndex("TenantId", "DataVencimento");

                    b.HasIndex("TenantId", "Status");

                    b.ToTable("sdr_tarefas", (string)null);
                });

            modelBuilder.Entity("LeadAnalytics.Api.Models.SdrTratamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("SdrConsultaId")
                        .HasColumnType("integer");

                    b.Property<int>("SdrLeadId")
                        .HasColumnType("integer");

                    b.Property<string>("Situacao")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("SdrConsultaId");

                    b.HasIndex("SdrLeadId");

                    b.HasIndex("TenantId", "CreatedAt");

                    b.ToTable("sdr_tratamentos", (string)null);
                });

            modelBuilder.Entity("LeadAnalytics.Api.Models.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClinicId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId")
                        .IsUnique();

                    b.ToTable("units", (string)null);
                });

            modelBuilder.Entity("LeadAnalytics.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("email");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("failed_login_attempts");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.Property<string>("PhotoPath")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("photo_path");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text")
                        .HasColumnName("refresh_token");

                    b.Property<DateTime?>("RefreshTokenExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_token_expires_at");

                    b.Property<int>("ResetPasswordAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("reset_password_attempts");

                    b.Property<DateTime?>("ResetPasswordCodeExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reset_password_code_expires_at");

                    b.Property<string>("ResetPasswordCodeHash")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reset_password_code_hash");

                    b.Property<DateTime?>("ResetPasswordRequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reset_password_requested_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("user")
                        .HasColumnName("role");

                    b.Property<int?>("TenantId")
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.Property<int?>("UnitId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UnitId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("LeadAnalytics.Api.Models.WebhookEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumberId")
                        .HasColumnType("text");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("WebhookEvents");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("LeadAnalytics.Api.Models.Attendant", b =>
                {
                    b.HasOne("LeadAnalytics.Api.Models.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("LeadAnalytics.Api.Models.Contact", b =>
                {
                    b.HasOne("LeadAnalytics.Api.Models.ImportBatch", "ImportBatch")
                        .WithMany()
                        .HasForeignKey("ImportBatchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ImportBatch");
                });

            modelBuilder.Entity("LeadAnalytics.Api.Models.Lead", b =>
                {
                    b.HasOne("LeadAnalytics.Api.Models.Attendant", "Attendant")
                        .WithMany()
                        .HasForeignKey("AttendantId");

                    b.HasOne("LeadAnalytics.Api.Models.Unit", "Unit")
                        .WithMany("Leads")
                        .HasForeignKey("UnitId");

                    b.Navigation("Attendant");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("LeadAnalytics.Api.Models.LeadAssignment", b =>
                {
                    b.HasOne("LeadAnalytics.Api.Models.Attendant", "Attendant")
                        .WithMany("Assignments")
                        .HasForeignKey("AttendantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeadAnalytics.Api.Models.Lead", "Lead")
                        .WithMany("Assignments")
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attendant");

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("LeadAnalytics.Api.Models.LeadAttribution", b =>
                {
                    b.HasOne("LeadAnalytics.Api.Models.OriginEvent", "OriginEvent")
                        .WithMany()
                        .HasForeignKey("OriginEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OriginEvent");
                });

            modelBuilder.Entity("LeadAnalytics.Api.Models.LeadConversation", b =>
                {
                    b.HasOne("LeadAnalytics.Api.Models.Attendant", "Attendant")
                        .WithMany()
                        .HasForeignKey("AttendantId");

                    b.HasOne("LeadAnalytics.Api.Models.Lead", "Lead")
                        .WithMany("Conversations")
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attendant");

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("LeadAnalytics.Api.Models.LeadInteraction", b =>
                {
                    b.HasOne("LeadAnalytics.Api.Models.LeadConversation", "Conversation")
                        .WithMany("Interactions")
                        .HasForeignKey("LeadConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("LeadAnalytics.Api.Models.LeadStageHistory", b =>
                {
                    b.HasOne("LeadAnalytics.Api.Models.Lead", "Lead")
                        .WithMany("StageHistory")
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("LeadAnalytics.Api.Models.OriginEvent", b =>
                {
                    b.HasOne("LeadAnalytics.Api.Models.WebhookEvent", "WebhookEvent")
                        .WithMany()
                        .HasForeignKey("WebhookEventId");

                    b.Navigation("WebhookEvent");
                });

            modelBuilder.Entity("LeadAnalytics.Api.Models.Payment", b =>
                {
                    b.HasOne("LeadAnalytics.Api.Models.Lead", "Lead")
                        .WithMany("Payments")
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeadAnalytics.Api.Models.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Lead");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("LeadAnalytics.Api.Models.PaymentSplit", b =>
                {
                    b.HasOne("LeadAnalytics.Api.Models.Payment", "Payment")
                        .WithMany("Splits")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("LeadAnalytics.Api.Models.SdrAgendaEvento", b =>
                {
                    b.HasOne("LeadAnalytics.Api.Models.SdrLead", "Lead")
                        .WithMany()
                        .HasForeignKey("SdrLeadId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("LeadAnalytics.Api.Models.SdrAuditLog", b =>
                {
                    b.HasOne("LeadAnalytics.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("LeadAnalytics.Api.Models.SdrConsulta", b =>
                {
                    b.HasOne("LeadAnalytics.Api.Models.SdrLead", "Lead")
                        .WithMany("Consultas")
                        .HasForeignKey("SdrLeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("LeadAnalytics.Api.Models.SdrLead", b =>
                {
                    b.HasOne("LeadAnalytics.Api.Models.ImportBatch", "ImportBatch")
                        .WithMany()
                        .HasForeignKey("ImportBatchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LeadAnalytics.Api.Models.User", "ReviewedByUser")
                        .WithMany()
                        .HasForeignKey("ReviewedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LeadAnalytics.Api.Models.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ImportBatch");

                    b.Navigation("ReviewedByUser");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("LeadAnalytics.Api.Models.SdrRecebimento", b =>
                {
                    b.HasOne("LeadAnalytics.Api.Models.SdrConsulta", "Consulta")
                        .WithMany("Recebimentos")
                        .HasForeignKey("SdrConsultaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LeadAnalytics.Api.Models.SdrTratamento", "Tratamento")
                        .WithMany("Recebimentos")
                        .HasForeignKey("SdrTratamentoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Consulta");

                    b.Navigation("Tratamento");
                });

            modelBuilder.Entity("LeadAnalytics.Api.Models.SdrTarefa", b =>
                {
                    b.HasOne("LeadAnalytics.Api.Models.SdrLead", "Lead")
                        .WithMany()
                        .HasForeignKey("SdrLeadId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("LeadAnalytics.Api.Models.SdrTratamento", b =>
                {
                    b.HasOne("LeadAnalytics.Api.Models.SdrConsulta", "Consulta")
                        .WithMany("Tratamentos")
                        .HasForeignKey("SdrConsultaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeadAnalytics.Api.Models.SdrLead", "Lead")
                        .WithMany()
                        .HasForeignKey("SdrLeadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Consulta");

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("LeadAnalytics.Api.Models.User", b =>
                {
                    b.HasOne("LeadAnalytics.Api.Models.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("LeadAnalytics.Api.Models.Attendant", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("LeadAnalytics.Api.Models.Lead", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Conversations");

                    b.Navigation("Payments");

                    b.Navigation("StageHistory");
                });

            modelBuilder.Entity("LeadAnalytics.Api.Models.LeadConversation", b =>
                {
                    b.Navigation("Interactions");
                });

            modelBuilder.Entity("LeadAnalytics.Api.Models.Payment", b =>
                {
                    b.Navigation("Splits");
                });

            modelBuilder.Entity("LeadAnalytics.Api.Models.SdrConsulta", b =>
                {
                    b.Navigation("Recebimentos");

                    b.Navigation("Tratamentos");
                });

            modelBuilder.Entity("LeadAnalytics.Api.Models.SdrLead", b =>
                {
                    b.Navigation("Consultas");
                });

            modelBuilder.Entity("LeadAnalytics.Api.Models.SdrTratamento", b =>
                {
                    b.Navigation("Recebimentos");
                });

            modelBuilder.Entity("LeadAnalytics.Api.Models.Unit", b =>
                {
                    b.Navigation("Leads");
                });
#pragma warning restore 612, 618
        }
    }
}
